---
title: "SARS-nCOV-19"
author: "MK"
date: "16 03 2020"
output: 
  rmarkdown::github_document:
    fig_width: 10
    fig_height: 8
    dev: png 
---

```{r setup, include=FALSE}
library(data.table)
library(tidyverse)
library(broom)
library(lubridate)
library(zoo)
library(ggthemes)
```


## Params

```{r, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
url_conf <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
url_dead <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"
lookup <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv"
MIN_CASES_CUM     <- 400000
MIN_DEATHS_CUM    <- 20000
MIN_DATE_TESTS <- "2020-03-10"
MIN_DATE       <- "2020-03-25"
TODAY          <- "2020-04-11"
TAKE_LOG <- TRUE
START_CASES_NO = 1
START_DEATHS_NO = 10
CHART_MAX = 10000000
countries_include = c("Poland", "Czechia", "Sweden", "Singapore", "Korea, South")
dead = FALSE
MA = 1
pc = TRUE
cumulative = TRUE
dailyRateChange = FALSE

labs_x = "Days from patient 0"
subtitle = NA
caption = "data source: github.com/CSSEGISandData/COVID-19"
legend_off = TRUE

```


## Calc

```{r,  echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
build_data <- function(START_CASES_NO = 1, dead=FALSE, MA = 1, cumulative = TRUE, pc = TRUE, START_DEATHS_NO = 1, dailyRateChange=FALSE){

  population <- fread("API_SP.POP.TOTL_DS2_en_csv_v2_866861.csv", header = TRUE) %>% 
    select(`Country Name`, `2018`) %>% 
    rename(country = `Country Name`, pop = `2018`) %>%
    mutate(pop = pop/1000000)

  land  <- fread("API_AG.LND.TOTL.K2_DS2_en_csv_v2_888929.csv", header = TRUE) %>% 
    select(`Country Name`, `2018`) %>% 
    rename(country = `Country Name`, land = `2018`)
  
  tests <- fread("Tests.csv", header = TRUE) %>%
    mutate(date = as.Date(date)) %>%
    mutate(
      country = ifelse(country == "Czech Republic", "Czechia",country),
      country = ifelse(country == "Iran (Islamic Republic of)", "Iran",country),
      country = ifelse(country == "Republic of Korea", "Korea, South",country),
      country = ifelse(country == "USA", "US",country),
      country = ifelse(country == "Mainland China", "China",country)
    ) %>%
    select(country,date,new_tests,tests_cumulative) %>%
    group_by(country) %>%
    filter(new_tests > 0) %>%
    mutate(test_latest = ifelse(date == max(date), 1, 0)) %>%
    ungroup(.) %>%
    rename(tests = tests_cumulative) %>%
    rename(tests_new = new_tests) %>%
    mutate(
      tests = case_when(cumulative == TRUE ~ tests, TRUE ~ tests_new*1.0),
      tests = case_when(MA > 1 ~ rollapply(tests,MA,mean,align='right',fill=NA_real_), TRUE ~ 1.0*tests)
    )
  
  policy <- 
    fread("Policy.csv", header = TRUE) %>% 
    mutate(
      date = as.Date(date_policy_intro, "%d.%m.%Y"),
      policy_intro = 1L
    )

  data <- 
    fread(ifelse(dead,url_dead,url_conf)) %>%
    melt(., id.vars = c(1,2,3,4)) %>% 
    mutate (date = as.Date(variable, format = "%m/%d/%y")) %>% 
    select(-variable) %>% 
    rename(country = `Country/Region`, province = `Province/State`) %>% 
    group_by(country, date) %>% 
    summarize(value = sum(value))
  
  data_first <- 
    data %>% 
    filter((dead == FALSE & value > START_CASES_NO) | (dead == TRUE & value > START_DEATHS_NO)) %>% 
    group_by(country) %>% 
    mutate(maxv = max(value)) %>% 
    top_n(-1, wt = date) %>% 
    select(country, date, maxv) %>% 
    rename(date_first = date)
  
  data_conf <- 
    data %>% 
    left_join(., data_first, by = "country") %>% 
    mutate(is_maxv = ifelse(value == maxv, 1, 0)) %>%
    mutate(days = date-date_first) %>% 
    filter(days >=0) %>% 
    mutate(
      value = case_when(cumulative == TRUE ~ value, TRUE ~ value -dplyr::lag(value)),
    ) %>%  
    left_join(., tests) %>%
    mutate(
      cases_per_test = case_when(MA > 1 ~ rollapply(value/tests,MA,mean,align='right',fill=NA_real_), TRUE ~ 1.0*value/tests)
    ) %>% 
    
    mutate(
      value = case_when(dailyRateChange == TRUE ~ value/lag(value) - 1, TRUE ~ 1.0 * value)
    ) %>%
    
    left_join(., population) %>% 
    mutate(
       value = case_when(MA > 1 ~ rollapply(value      ,MA,mean,align='right',fill=NA_real_), TRUE ~ 1.0*value),
       value = case_when(pc == TRUE ~ value/pop, TRUE ~ 1.0*value),
       tests = case_when(pc == TRUE ~ tests/pop, TRUE ~ 1.0*tests)
    ) %>%
    
    left_join(., land) %>%
    mutate(pop_density = pop/land) %>%
    select(-date_first, -pop) %>%
    
    left_join(., policy, by = c("country", "date")) %>%
    mutate(policy_intro = ifelse(policy_intro == 1, 1, 0))

  MIN_VALUE <- if_else(dead == FALSE, MIN_CASES_CUM, MIN_DEATHS_CUM)

  conf_filtered <- 
    data_conf %>% 
    filter(
      (
        maxv > MIN_VALUE 
        & country != "China" 
      ) 
      | country %in% countries_include
      ) %>%
    filter(value < CHART_MAX)
  
  return(conf_filtered)
}

formatBack <- function(x) 10^x 

plot_chart <- function(
  data,
  TAKE_LOG,
  dead = FALSE,
  labs_y, 
  labs_x = "Days from patient 0",
  title, 
  subtitle = NA,
  caption = "data source: github.com/CSSEGISandData/COVID-19", 
  legend_off = TRUE
 ){
  
  data <- data %>%
    mutate(
      value = if(TAKE_LOG) log10(value)   else value
    )
  
  if(is.na(subtitle)){
    subtitle <- paste0("countries > ", ifelse(dead, MIN_DEATHS_CUM, MIN_CASES_CUM)," + ",paste(countries_include,collapse=", "))
  }
  
  
  g <- 
    ggplot(data, aes(days, value, colour = country)) + 
    geom_point(alpha = 0.7, size = 1) + 
    geom_line(alpha = 0.2) +
    geom_text(data = data %>% filter(is_maxv == 1), aes(label = country, colour = country, x = days, y = value), hjust = -.1, size = 3) +
    geom_point(data = data %>% filter(policy_intro == 1), aes(colour = country, x = days, y = value), alpha = 1, size = 2) +
    labs(y=labs_y, x = labs_x) +
    labs(title = title, subtitle = subtitle) +
    labs(caption = caption) +
    #scale_color_tableau(palette = "Tableau 10") +
    (if(TAKE_LOG) scale_y_continuous(labels = formatBack) ) +
    (if(legend_off) theme(legend.position="none"))
  
  return(g)
}

```


## Plots

### 1. log10(number of cases)

Removed.

```{r, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
# plot_chart(data = build_data(START_CASES_NO = 1),
#            TAKE_LOG = TRUE,
#            labs_y = "log10(Number of cases)",
#            title = "1.1 log10(Number of cases), Day 0 = 1 case",
#            )
```


```{r, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
# plot_chart(data = build_data(START_CASES_NO = 30),
#            TAKE_LOG = TRUE,
#            labs_y = "log10(Number of cases)",
#            title = "1.2 log10(Number of cases), Day 0 = 30 cases"
#            )

```

### 2. Nominal number of cases

Removed.

### 3. Nominal number of cases per 1M inhabitants

```{r, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
# plot_chart(data = build_data(START_CASES_NO = 1),
#           TAKE_LOG = FALSE,
#           labs_y = "Number of cases per 1M inhabitants",
#           title = "3.1 Number of cases per 1M inhabitans, Day 0 = 1 case"
#           )
```


```{r, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}

plot_chart(data = build_data(START_CASES_NO = 100),
          TAKE_LOG = FALSE,
          labs_y = "Cumulative number of cases per 1M inhabitants",
          title = "3.2 Cumulative number of cases per 1M inhabitans, Day 0 = 100 cases"
          )
```

```{r, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
plot_chart(data = build_data(START_CASES_NO = 100, cumulative = FALSE, MA = 7),
          TAKE_LOG = FALSE,
          dead = FALSE,
          labs_y = "Number of cases per 1M inhabitants, 7-day moving average",
          title = "3.3 Number of cases per 1M inhabitans, Day 0 = 100 cases, 7-day moving average"
          )
```

```{r, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
MIN_CASES_CUM     <- 2000000
countries_include = c("Poland", "Czechia", "Sweden", "Singapore", "Korea, South", "UK", "Italy")
plot_chart(data = build_data(START_CASES_NO = 100, dead = FALSE, cumulative = FALSE, MA = 14, dailyRateChange = TRUE, pc = FALSE) %>% filter(value < 1 & value > -0.2),
          TAKE_LOG = FALSE,
          dead = FALSE,
          labs_y = "Change in daily rate, 14-day moving average",
          title = "3.4 Change in daily rate, Day 0 = 100 cases, 14-day moving average"
          )
MIN_CASES_CUM     <- 80000
countries_include = c("Poland", "Czechia", "Sweden", "Singapore", "Korea, South")
```


### 4. Log(10) number of cases per 1M inhabitants

```{r, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
plot_chart(data = build_data(START_CASES_NO = 100, cumulative = FALSE, MA = 7),
          TAKE_LOG = TRUE,
          dead = FALSE,
          labs_y = "Log(10) number of cases per 1M inhabitants, 7-day moving average",
          title = "4.1 Log(10) number of cases per 1M inhabitans, Day 0 = 100 cases, 7-day moving average"
          )
```

### 5. Tests

Idea: https://ourworldindata.org/grapher/tests-vs-confirmed-cases-covid-19-per-million

```{r, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}

conf_filtered <- build_data(START_CASES_NO = 100, cumulative = TRUE) %>%
  filter(value >0 & tests > 0) %>%
  mutate(tests = log10(tests)) %>%
  mutate(cases_per_test = log10(cases_per_test)) %>%
  filter(date > MIN_DATE_TESTS)


ggplot(conf_filtered, aes(tests, cases_per_test, colour = country)) + 
  geom_text(data = conf_filtered %>% filter(test_latest == 0), aes(label = day(date), colour = country, x = tests, y = cases_per_test), size = 2, alpha = 0.5) +
  geom_line(alpha = 0.3) +
  geom_text(data = conf_filtered %>% filter(test_latest == 1), aes(label = country, colour = country, x = tests, y = cases_per_test), nudge_y = 0.02, size = 3) +
  geom_text(data = conf_filtered %>% filter(test_latest == 1), aes(label = day(date), colour = country, x = tests, y = cases_per_test), size = 3) +
  labs(y="Log Number of cases per 1 test, cumulative", x = "Number of tests per 1M inhabitants, cumulative") +
  labs(title = "5.1 Log Number of tests per 1M inhabitants vs cases per test, cumulative", subtitle = paste0("countries > ",MIN_CASES_CUM," nominal cases + Poland. Point label = date")) +
  labs(caption = "source: github.com/CSSEGISandData/COVID-19, finddx.org/covid-19/test-tracker") +
  theme(legend.position = "none")
```

```{r, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
# conf_filtered <- build_data(START_CASES_NO = 1, cumulative = FALSE) %>%
#   filter(value > 0 & tests > 0) %>%
#   mutate(tests = log10(tests)) %>%
#   mutate(cases_per_test = log10(cases_per_test)) %>%
#   filter(date > MIN_DATE_TESTS)
# 
# 
# ggplot(conf_filtered, aes(tests, cases_per_test, colour = country)) + 
#   geom_text(data = conf_filtered %>% filter(test_latest == 0), aes(label = day(date), colour = country, x = tests, y = cases_per_test), size = 2, alpha = 0.5) +
#   geom_line(alpha = 0.3) +
#   geom_text(data = conf_filtered %>% filter(test_latest == 1), aes(label = country, colour = country, x = tests, y = cases_per_test), nudge_y = 0.02, size = 3) +
#   geom_text(data = conf_filtered %>% filter(test_latest == 1), aes(label = day(date), colour = country, x = tests, y = cases_per_test), size = 3) +
#   lims(x= c(1,10), y = c(-7, 0)) +
#   labs(y="Log of Number of new cases per 1 new test", x = "Log of Number of new tests per 1M inhabitants") +
#   labs(title = "5.2 Log Number of new tests per 1M inhabitants vs log new cases per 1 new test", subtitle = paste0("countries > ",MIN_CASES_CUM," nominal cases + Poland. Point label = date")) +
#   labs(caption = "source: github.com/CSSEGISandData/COVID-19, finddx.org/covid-19/test-tracker")
```

### 6. Forecast

Removed.

### 7. Deaths (cumulative)

```{r, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}

plot_chart(data = build_data(START_DEATHS_NO = 10, dead = TRUE),
          TAKE_LOG = TRUE,
          dead = TRUE,
          labs_y = "Logged cumulative number of deaths per 1M inhabitants",
          title = "7.1 Logged cumulative number of deaths per 1M inhabitans, Day 0 = 10 deaths",
          )
```

```{r, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
plot_chart(data = build_data(START_DEATHS_NO = 10, dead = TRUE),
          TAKE_LOG = FALSE,
          dead = TRUE,
          labs_y = "Cumulative number of deaths per 1M inhabitants",
          title = "7.2 Cumulative number of deaths per 1M inhabitans, Day 0 = 10 deaths"
          )

```

### 8. Deaths

```{r, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}

plot_chart(data = build_data(START_DEATHS_NO = 10, dead = TRUE, cumulative = FALSE, MA = 7),
          TAKE_LOG = TRUE,
          dead = TRUE,
          labs_y = "Logged number of deaths per 1M inhabitants, 3-day moving average",
          title = "8.1 Logged number of deaths per 1M inhabitans, Day 0 = 10 deaths, 7-day moving average"
          )
```

```{r, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
plot_chart(data = build_data(START_DEATHS_NO = 10, dead = TRUE, cumulative = FALSE, MA = 7),
          TAKE_LOG = FALSE,
          dead = TRUE,
          labs_y = "Logged number of deaths per 1M inhabitants, 3-day moving average",
          title = "8.2 Number of deaths per 1M inhabitans, Day 0 = 10 deaths, 7-day moving average"
          )
```


```{r, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
MIN_DEATHS_CUM    <- 10000
plot_chart(data = build_data(START_DEATHS_NO = 10, dead = TRUE, cumulative = FALSE, MA = 14, dailyRateChange = TRUE, pc = FALSE) %>% filter(value < 1 & value > -0.2),
          TAKE_LOG = FALSE,
          dead = TRUE,
          labs_y = "Change in daily death rate, 14-day moving average",
          title = "8.3 Change in daily death rate, Day 0 = 2 deaths, 14-day moving average"
          )
```

